[package]
name = "tsp-sol"
version = "0.1.0"
edition = "2018"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]

[dependencies]
tsplib = "0.1"
image = "0.23"
imageproc = { version = "0.22", default-features = false }
rusttype = "0.9"
rand = "0.5"
permutohedron = "0.2"
factorial = "0.2"


