[package]
name = "tsp-sol"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]

[dependencies]
tsplib = "0.1.0"
#image = "*"
image = "0.20.1"
imageproc = "0.16.0"
#rusttype = "*"
rusttype = "0.5.2"
rand = "0.5.5"
permutohedron = "0.2.4"



